// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Return 0 if a and b are equal, -1 otherwise
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external int crypto_verify16(
  ffi.Pointer<ffi.Uint8> a,
  ffi.Pointer<ffi.Uint8> b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external int crypto_verify32(
  ffi.Pointer<ffi.Uint8> a,
  ffi.Pointer<ffi.Uint8> b,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external int crypto_verify64(
  ffi.Pointer<ffi.Uint8> a,
  ffi.Pointer<ffi.Uint8> b,
);

/// Erase sensitive data
/// --------------------
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Size)>()
external void crypto_wipe(ffi.Pointer<ffi.Void> secret, int size);

/// Authenticated encryption
/// ------------------------
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_aead_lock(
  ffi.Pointer<ffi.Uint8> cipher_text,
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_size,
  ffi.Pointer<ffi.Uint8> plain_text,
  int text_size,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int crypto_aead_unlock(
  ffi.Pointer<ffi.Uint8> plain_text,
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_size,
  ffi.Pointer<ffi.Uint8> cipher_text,
  int text_size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_aead_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_aead_init_x(
  ffi.Pointer<crypto_aead_ctx> ctx,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_aead_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_aead_init_djb(
  ffi.Pointer<crypto_aead_ctx> ctx,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_aead_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_aead_init_ietf(
  ffi.Pointer<crypto_aead_ctx> ctx,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_aead_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_aead_write(
  ffi.Pointer<crypto_aead_ctx> ctx,
  ffi.Pointer<ffi.Uint8> cipher_text,
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_size,
  ffi.Pointer<ffi.Uint8> plain_text,
  int text_size,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<crypto_aead_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int crypto_aead_read(
  ffi.Pointer<crypto_aead_ctx> ctx,
  ffi.Pointer<ffi.Uint8> plain_text,
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> ad,
  int ad_size,
  ffi.Pointer<ffi.Uint8> cipher_text,
  int text_size,
);

/// Direct interface
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_blake2b(
  ffi.Pointer<ffi.Uint8> hash,
  int hash_size,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_blake2b_keyed(
  ffi.Pointer<ffi.Uint8> hash,
  int hash_size,
  ffi.Pointer<ffi.Uint8> key,
  int key_size,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<crypto_blake2b_ctx>, ffi.Size)>()
external void crypto_blake2b_init(
  ffi.Pointer<crypto_blake2b_ctx> ctx,
  int hash_size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_blake2b_ctx>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_blake2b_keyed_init(
  ffi.Pointer<crypto_blake2b_ctx> ctx,
  int hash_size,
  ffi.Pointer<ffi.Uint8> key,
  int key_size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_blake2b_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_blake2b_update(
  ffi.Pointer<crypto_blake2b_ctx> ctx,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<crypto_blake2b_ctx>, ffi.Pointer<ffi.Uint8>)
>()
external void crypto_blake2b_final(
  ffi.Pointer<crypto_blake2b_ctx> ctx,
  ffi.Pointer<ffi.Uint8> hash,
);

@ffi.Native<crypto_argon2_extras>()
external final crypto_argon2_extras crypto_argon2_no_extras;

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Pointer<ffi.Void>,
    crypto_argon2_config,
    crypto_argon2_inputs,
    crypto_argon2_extras,
  )
>()
external void crypto_argon2(
  ffi.Pointer<ffi.Uint8> hash,
  int hash_size,
  ffi.Pointer<ffi.Void> work_area,
  crypto_argon2_config config,
  crypto_argon2_inputs inputs,
  crypto_argon2_extras extras,
);

/// Shared secrets are not quite random.
/// Hash them to derive an actual shared key.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_x25519_public_key(
  ffi.Pointer<ffi.Uint8> public_key,
  ffi.Pointer<ffi.Uint8> secret_key,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_x25519(
  ffi.Pointer<ffi.Uint8> raw_shared_secret,
  ffi.Pointer<ffi.Uint8> your_secret_key,
  ffi.Pointer<ffi.Uint8> their_public_key,
);

/// Conversion to EdDSA
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_x25519_to_eddsa(
  ffi.Pointer<ffi.Uint8> eddsa,
  ffi.Pointer<ffi.Uint8> x25519,
);

/// scalar "division"
/// Used for OPRF.  Be aware that exponential blinding is less secure
/// than Diffie-Hellman key exchange.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_x25519_inverse(
  ffi.Pointer<ffi.Uint8> blind_salt,
  ffi.Pointer<ffi.Uint8> private_key,
  ffi.Pointer<ffi.Uint8> curve_point,
);

/// "Dirty" versions of x25519_public_key().
/// Use with crypto_elligator_rev().
/// Leaks 3 bits of the private key.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_x25519_dirty_small(
  ffi.Pointer<ffi.Uint8> pk,
  ffi.Pointer<ffi.Uint8> sk,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_x25519_dirty_fast(
  ffi.Pointer<ffi.Uint8> pk,
  ffi.Pointer<ffi.Uint8> sk,
);

/// EdDSA with curve25519 + BLAKE2b
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_eddsa_key_pair(
  ffi.Pointer<ffi.Uint8> secret_key,
  ffi.Pointer<ffi.Uint8> public_key,
  ffi.Pointer<ffi.Uint8> seed,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_eddsa_sign(
  ffi.Pointer<ffi.Uint8> signature,
  ffi.Pointer<ffi.Uint8> secret_key,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int crypto_eddsa_check(
  ffi.Pointer<ffi.Uint8> signature,
  ffi.Pointer<ffi.Uint8> public_key,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

/// Conversion to X25519
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_eddsa_to_x25519(
  ffi.Pointer<ffi.Uint8> x25519,
  ffi.Pointer<ffi.Uint8> eddsa,
);

/// EdDSA building blocks
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_eddsa_trim_scalar(
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Uint8> in$,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_eddsa_reduce(
  ffi.Pointer<ffi.Uint8> reduced,
  ffi.Pointer<ffi.Uint8> expanded,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_eddsa_mul_add(
  ffi.Pointer<ffi.Uint8> r,
  ffi.Pointer<ffi.Uint8> a,
  ffi.Pointer<ffi.Uint8> b,
  ffi.Pointer<ffi.Uint8> c,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_eddsa_scalarbase(
  ffi.Pointer<ffi.Uint8> point,
  ffi.Pointer<ffi.Uint8> scalar,
);

@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external int crypto_eddsa_check_equation(
  ffi.Pointer<ffi.Uint8> signature,
  ffi.Pointer<ffi.Uint8> public_key,
  ffi.Pointer<ffi.Uint8> h_ram,
);

/// Specialised hash.
/// Used to hash X25519 shared secrets.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_chacha20_h(
  ffi.Pointer<ffi.Uint8> out,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> in$,
);

/// Unauthenticated stream cipher.
/// Don't forget to add authentication.
@ffi.Native<
  ffi.Uint64 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>()
external int crypto_chacha20_djb(
  ffi.Pointer<ffi.Uint8> cipher_text,
  ffi.Pointer<ffi.Uint8> plain_text,
  int text_size,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
  int ctr,
);

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
  )
>()
external int crypto_chacha20_ietf(
  ffi.Pointer<ffi.Uint8> cipher_text,
  ffi.Pointer<ffi.Uint8> plain_text,
  int text_size,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
  int ctr,
);

@ffi.Native<
  ffi.Uint64 Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>()
external int crypto_chacha20_x(
  ffi.Pointer<ffi.Uint8> cipher_text,
  ffi.Pointer<ffi.Uint8> plain_text,
  int text_size,
  ffi.Pointer<ffi.Uint8> key,
  ffi.Pointer<ffi.Uint8> nonce,
  int ctr,
);

/// Direct interface
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_poly1305(
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
  ffi.Pointer<ffi.Uint8> key,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<crypto_poly1305_ctx>, ffi.Pointer<ffi.Uint8>)
>()
external void crypto_poly1305_init(
  ffi.Pointer<crypto_poly1305_ctx> ctx,
  ffi.Pointer<ffi.Uint8> key,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<crypto_poly1305_ctx>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external void crypto_poly1305_update(
  ffi.Pointer<crypto_poly1305_ctx> ctx,
  ffi.Pointer<ffi.Uint8> message,
  int message_size,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<crypto_poly1305_ctx>, ffi.Pointer<ffi.Uint8>)
>()
external void crypto_poly1305_final(
  ffi.Pointer<crypto_poly1305_ctx> ctx,
  ffi.Pointer<ffi.Uint8> mac,
);

/// Elligator mappings proper
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>()
external void crypto_elligator_map(
  ffi.Pointer<ffi.Uint8> curve,
  ffi.Pointer<ffi.Uint8> hidden,
);

@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, ffi.Uint8)
>()
external int crypto_elligator_rev(
  ffi.Pointer<ffi.Uint8> hidden,
  ffi.Pointer<ffi.Uint8> curve,
  int tweak,
);

/// Easy to use key pair generation
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
  )
>()
external void crypto_elligator_key_pair(
  ffi.Pointer<ffi.Uint8> hidden,
  ffi.Pointer<ffi.Uint8> secret_key,
  ffi.Pointer<ffi.Uint8> seed,
);

/// Authenticated stream
/// --------------------
final class crypto_aead_ctx extends ffi.Struct {
  @ffi.Uint64()
  external int counter;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Uint8> key;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint8> nonce;
}

/// Incremental interface
final class crypto_blake2b_ctx extends ffi.Struct {
  /// Do not rely on the size or contents of this type,
  /// for they may change without notice.
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Uint64> hash;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Uint64> input_offset;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint64> input;

  @ffi.Size()
  external int input_idx;

  @ffi.Size()
  external int hash_size;
}

final class crypto_argon2_config extends ffi.Struct {
  /// Argon2d, Argon2i, Argon2id
  @ffi.Uint32()
  external int algorithm;

  /// memory hardness, >= 8 * nb_lanes
  @ffi.Uint32()
  external int nb_blocks;

  /// CPU hardness, >= 1 (>= 3 recommended for Argon2i)
  @ffi.Uint32()
  external int nb_passes;

  /// parallelism level (single threaded anyway)
  @ffi.Uint32()
  external int nb_lanes;
}

final class crypto_argon2_inputs extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> pass;

  external ffi.Pointer<ffi.Uint8> salt;

  @ffi.Uint32()
  external int pass_size;

  /// 16 bytes recommended
  @ffi.Uint32()
  external int salt_size;
}

final class crypto_argon2_extras extends ffi.Struct {
  /// may be NULL if no key
  external ffi.Pointer<ffi.Uint8> key;

  /// may be NULL if no additional data
  external ffi.Pointer<ffi.Uint8> ad;

  /// 0 if no key (32 bytes recommended otherwise)
  @ffi.Uint32()
  external int key_size;

  /// 0 if no additional data
  @ffi.Uint32()
  external int ad_size;
}

/// Incremental interface
final class crypto_poly1305_ctx extends ffi.Struct {
  /// chunk of the message
  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> c;

  /// How many bytes are there in the chunk.
  @ffi.Size()
  external int c_idx;

  /// constant multiplier (from the secret key)
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint32> r;

  /// random number added at the end (from the secret key)
  @ffi.Array.multi([4])
  external ffi.Array<ffi.Uint32> pad;

  /// accumulated hash
  @ffi.Array.multi([5])
  external ffi.Array<ffi.Uint32> h;
}

const int CRYPTO_ARGON2_D = 0;

const int CRYPTO_ARGON2_I = 1;

const int CRYPTO_ARGON2_ID = 2;
